#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/setup-ios-local-signing.sh [--team-id <TEAMID>] [--bundle-id <BUNDLEID>] [--force] [--non-interactive]

Creates/updates `ios/FeedFlow/Config/FeedFlow.local.xcconfig` (gitignored) so Xcode can sign without modifying
`ios/FeedFlow.xcodeproj/project.pbxproj` on each machine.

Tip (recommended): run `./scripts/install-githooks.sh` once to generate this file automatically after `git pull`.

Options:
  --team-id <TEAMID>       Override detected Apple Team ID (10 chars, e.g. ABCDE12345)
  --bundle-id <BUNDLEID>   Override generated bundle identifier (e.g. com.yourname.feedflow)
  --force                 Overwrite existing local xcconfig
  --non-interactive        Pick the first Team ID when multiple are found (prints a warning)
EOF
}

team_id=""
bundle_id=""
force=0
non_interactive=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --team-id)
      team_id="${2:-}"
      shift 2
      ;;
    --bundle-id)
      bundle_id="${2:-}"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --non-interactive)
      non_interactive=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
config_dir="$repo_root/ios/FeedFlow/Config"
local_xcconfig="$config_dir/FeedFlow.local.xcconfig"

if [[ ! -d "$config_dir" ]]; then
  echo "Missing directory: $config_dir" >&2
  exit 1
fi

existing_bundle_id=""
existing_team_id=""

if [[ -f "$local_xcconfig" && "$force" != "1" ]]; then
  existing_team_id="$(sed -n 's/^[[:space:]]*FEEDFLOW_DEVELOPMENT_TEAM[[:space:]]*=[[:space:]]*\\([A-Z0-9]\\{10\\}\\).*/\\1/p' "$local_xcconfig" | head -n 1 || true)"
  if [[ -z "$existing_team_id" ]]; then
    existing_team_id="$(sed -n 's/^[[:space:]]*DEVELOPMENT_TEAM[[:space:]]*=[[:space:]]*\\([A-Z0-9]\\{10\\}\\).*/\\1/p' "$local_xcconfig" | head -n 1 || true)"
  fi

  existing_bundle_id="$(sed -n 's/^[[:space:]]*FEEDFLOW_BUNDLE_ID[[:space:]]*=[[:space:]]*\\([^[:space:]]\\+\\).*/\\1/p' "$local_xcconfig" | head -n 1 || true)"
  if [[ -z "$existing_bundle_id" ]]; then
    existing_bundle_id="$(sed -n 's/^[[:space:]]*PRODUCT_BUNDLE_IDENTIFIER[[:space:]]*=[[:space:]]*\\([^[:space:]]\\+\\).*/\\1/p' "$local_xcconfig" | head -n 1 || true)"
  fi

  if [[ -n "$existing_team_id" ]]; then
    echo "Already configured: $local_xcconfig"
    echo "DEVELOPMENT_TEAM=$existing_team_id"
    exit 0
  fi

  echo "Found existing local xcconfig, but Team ID is missing; overwriting: $local_xcconfig" >&2
  if [[ -n "$existing_bundle_id" && -z "$bundle_id" ]]; then
    bundle_id="$existing_bundle_id"
  fi
fi

if [[ -z "$team_id" ]]; then
  if ! command -v security >/dev/null 2>&1; then
    echo "Cannot auto-detect Team ID: 'security' command not found (macOS only)." >&2
    echo "Provide it via --team-id ABCDE12345" >&2
    exit 1
  fi

  teams_list="$(security find-identity -p codesigning -v 2>/dev/null \
    | sed -n 's/.*\"Apple Development:.*(\\([A-Z0-9]\\{10\\}\\))\".*/\\1/p' \
    | sort -u \
    || true)"

  if [[ -z "$teams_list" ]]; then
    echo "No Apple Development Team ID found in code signing identities." >&2
    echo "Make sure you have an 'Apple Development' certificate installed in Keychain Access." >&2
    exit 1
  fi

  team_ids=()
  while IFS= read -r t; do
    [[ -n "$t" ]] && team_ids+=("$t")
  done <<< "$teams_list"

  if [[ "${#team_ids[@]}" == "1" ]]; then
    team_id="${team_ids[0]}"
  else
    if [[ "$non_interactive" == "1" ]]; then
      team_id="${team_ids[0]}"
      echo "Multiple Team IDs found; using $team_id. Override with --team-id <TEAMID> if needed." >&2
      echo "$teams_list" >&2
    else
      echo "Multiple Team IDs found:"
      PS3="Select Team ID: "
      select picked in "${team_ids[@]}"; do
        if [[ -n "${picked:-}" ]]; then
          team_id="$picked"
          break
        fi
        echo "Invalid selection."
      done
    fi
  fi
fi

if [[ -z "$team_id" ]]; then
  echo "Missing Team ID." >&2
  exit 1
fi

if [[ -z "$bundle_id" ]]; then
  team_lower="$(echo "$team_id" | tr '[:upper:]' '[:lower:]')"
  bundle_id="com.team${team_lower}.feedflow"
fi

mkdir -p "$config_dir"

cat > "$local_xcconfig" <<EOF
// Auto-generated by scripts/setup-ios-local-signing.sh
// This file is gitignored and intended to be machine-specific.
//
// If you hit "bundle identifier not available", change PRODUCT_BUNDLE_IDENTIFIER to a unique value you own.

FEEDFLOW_DEVELOPMENT_TEAM = $team_id
FEEDFLOW_BUNDLE_ID = $bundle_id
EOF

echo "Wrote: $local_xcconfig"
echo "DEVELOPMENT_TEAM=$team_id"
echo "BUNDLE_ID=$bundle_id"
echo "Tip: run ./scripts/install-githooks.sh once to auto-generate this after git pull."
